### ISSUE TITLE
latest_lumen.zip is downloaded over HTTP instead of HTTPS

### ISSUE THREAD

**Issue by HenkPoley** [laravel/lumen-installer#21]
Code here: https://github.com/laravel/lumen-installer/blob/master/src/NewCommand.php#L108

**Comment by driesvints** [comment]
We're looking into this but it could be a while before we can update this.

**Comment by driesvints** [comment]
We probably won't be change this anytime soon. The current installers are working fine.

**Comment by 8ctopus** [comment]
ems not serious, can't you install a letsencrypt certificate on cabinet.laravel.com? should not take more than 10 minutes.
