### ISSUE TITLE
Installation some laravel dependencies when to create lumen project.

### ISSUE THREAD

**Issue by pronist** [laravel/lumen-installer#22]
When i develop small application with lumen, sometimes i need **laravel dependencies** such as laravel session. I don't know how to use, or install laravel features in lumen project. I have found solution on google. But, it's so uncomfortable. 

Could you append feature that **generate lumen project with some laravel dependencies through developer selection** when i execute command ```lumen new <project_name>``` ?

**Comment by driesvints** [comment]
Just use composer afterwards to install any packages you need. However, if you need more illuminate components I suggest you use the Laravel framework instead. Lumen was only meant to work with the components it ships with.
