### ISSUE TITLE
Lumen now requires PHP 7.3

### ISSUE THREAD

**Issue by davehasagithub** [laravel/lumen-installer#29]
- Lumen Installer Version: 1.1.1

### Description:

Server requirements show "PHP >= **7.2**" (https://lumen.laravel.com/docs/7.x#server-requirements).

But, when I try to run "lumen new", it says:

>Your requirements could not be resolved to an installable set of packages.
>mockery/mockery 1.4.0 requires php **^7.3.0** -> your PHP version (7.2.10) does not satisfy that requirement.

It looks like the installer uses cabinet.laravel.com/latest_lumen.zip. The composer.lock file inside shows that it was modified less than a day ago. It includes mockery 1.4 which requires PHP 7.3. Is there an easy workaround to use 7.2 again?

Sorry if I'm misunderstanding. Thanks for any insights!

### Steps To Reproduce:

lumen new <project name>

**Comment by driesvints** [comment]
We had the same issue on the laravel installer so we had to make the installer require 7.3 as a minimum version. We'll have to do this for the lumen installer as well.

We had the same issue on the laravel installer so we had to make the installer require 7.3 as a minimum version

Lumen itself still works on 7.2 btw. You'll have to use `composer create-project laravel/lumen` to install it.

**Comment by davehasagithub** [comment]
Thank you! I appreciate the quick response and the _create-project_ workaround. I should have looked for the laravel installer issue first (https://github.com/laravel/installer/issues/117).

**Comment by driesvints** [comment]
I've pushed this change now. Will be released on Tuesday.
